# Generated by Django 5.0.4 on 2024-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_citizenship_item_college_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.DateField(default='2000-01-01', null=True),
        ),
    ]
